[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://geoprop-ai-backend.up.railway.app"