[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && pip install -r backend/requirements.txt"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10