apiVersion: v1 
kind: Service 
metadata: 
  name: geoprop-api-service 
spec: 
  selector: 
    app: geoprop-api 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 8000 
  type: LoadBalancer 
